### ISSUE TITLE
The script don't compile ffplay.

### ISSUE THREAD

**Issue by DarbyCrash** [stvs/ffmpeg-static#35]
How can i compile also ffplay with your script on Debian?

Many thanks for your work! ;)

**Comment by michalliu** [comment]
My fork will compile latest ffmpeg with ffplay and ffserver support
https://github.com/michalliu/ffmpeg-static

**Comment by michalliu** [comment]
I just send a pull request, maybe this project is abandoned.
https://github.com/stvs/ffmpeg-static/pull/36

**Comment by zimbatm** [comment]
I'm happy to accept new PRs but don't have the time to maintain the project myself.
